# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-errors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy-analyse:
    runs-on: ubuntu-latest
    needs: check-errors
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Clippy analysis
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  run-tests:
    runs-on: ubuntu-latest
    needs: check-errors
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  auto-format:
    runs-on: ubuntu-latest
    needs: check-errors
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Auto-format with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Configure git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Formatted with rustfmt [${{ github.run_number }}]"
          git push

  publish-docs:
    runs-on: ubuntu-latest
    needs: auto-format
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Checkout docs
        uses: actions/checkout@v3
        with:
          ref: docs
          path: docs

      - name: Generate documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --workspace --document-private-items

      - name: Replace previous documentation
        run: |
          rm -r docs/doc
          cp -r target/doc docs/

      - name: Configure git credentials
        working-directory: docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit and push changes
        working-directory: docs
        run: |
          git add .
          git commit --allow-empty -m "Regenerated documentation [${{ github.run_number }}]"
          git push
